version: '2'
services:
  plex:
    image: plexinc/pms-docker
    environment:
      - TZ:america/los_angeles
      - PLEX_CLAIM:l
      - ADVERTISE_IP:http://10.0.2.2:32400
      - PLEX_UID:1000
      - PLEX_GID:1000
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - /var/media:/data
      - /var/media/tmp:/transcode
      - ./files/config:config
    