version: '2'
services:
  haproxy:
    extends:
      file: haproxy/docker-compose.yml
      service: haproxy

  consul:
    extends:
      file: consul/docker-compose.yml
      service: consul
  
  booksonic:
    extends:
      file: booksonic/docker-compose.yml
      service: booksonic

  registrator:
    extends:
      file: registrator/docker-compose.yml
      service: registrator
    depends_on: 
      - consul
      
  deluge:
    extends:
      file: deluge/docker-compose.yml
      service: deluge

  plex:
    extends:
      file: plex/docker-compose.yml
      service: plex
